# Generated by Django 4.1.7 on 2023-05-15 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserLogin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=200)),
                ("username", models.CharField(max_length=15)),
                ("password", models.CharField(max_length=10)),
                ("Phone_no", models.IntegerField()),
                ("state", models.CharField(max_length=20)),
            ],
        ),
    ]
